name: Build

on:
  push:
    branches:
      - master


 
  
  deploy:
   needs: build
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull aakibkhan1212/swiggy-clone:latest
      - name: Image scan
        run: trivy image aakibkhan1212/swiggy-clone:latest > trivyimagedeploy.txt
      - name: Deploy to container
        run: docker run -d --name swiggy-clone1 -p 3000:3000 aakibkhan1212/swiggy-clone:latest
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
